### ISSUE TITLE
Pylint error: Accessing a protected member of a client class when calling functions on the DWX_ZeroMQ_Connector.py

### ISSUE THREAD

**Issue by teddywaweru** [darwinex/dwx-zeromq-connector#141]
I've been trying to implement the DWX_connector & making reference calls to the functions on the script. But now my code is having all these Pylint warnings concerning:
`Access to a protected member _DWX_MTX_UNSUBSCRIBE_MARKETDATA_ of a client class pylint(protected-access)`
On browsing the error, it turns out that Pylint recognizes objects starting with an underscore as protected.
Wondering whether:
1. Is this a PEP design guideline?
2. Am I the only facing this issue? or how do i bypass it...

**Comment by elvinex** [comment]
Hi,

As google tellsme, the underscore seems to indicates that the variable or method is intended for internal use. 

But I am not sure if that is the case for all of the occurrences or whether it was simply a preference of the programmer who wrote the ZeroMQ Connector. 

Now, I wouldn't want to change variable/method names since it would force users to also change all their code.
