### ISSUE TITLE
uninit reason 4 error

### ISSUE THREAD

**Issue by pwerspire** [darwinex/dwx-zeromq-connector#40]
Hi,
Sometimes I receive this uninit reason 4 and don't know why:

2019.09.11 01:25:15.010	DWX_ZeroMQ_Server_v2.0.1_RC8 USDCHF,H1: [PUSH] Unbinding MT4 Server from Socket on Port 32769..
2019.09.11 01:25:15.008	DWX_ZeroMQ_Server_v2.0.1_RC8 USDCHF,H1: uninit reason 4

Any extra logs that I can get to try found out what is causing it? at the time that error appears I wan't doing nothing, the DWX_ZeroMQ_Server_v2.0.1_RC8.mq4 was just running

thanks

**Comment by integracore2** [comment]
Hi @pwerspire ,

**uninit reason 4** can often be raised due to dependency DLLs either missing or not installed correctly as per the provided README.

Kindly ensure you are using the latest files from the v2.0.1 repository, and have **Allow DLL imports** enabled in both MetaTrader 4's terminal Options and the EA's **Inputs** tab.

For more information on diagnosing and resolving this, please watch the following YouTube playlist dedicated to installation & configuration of the dwx-zeromq-connector project:
https://www.youtube.com/playlist?list=PLv-cA-4O3y97vTpghgRqiPBjmpgWskYDl
